services:
  db:
    image: mariadb:latest
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --log-bin=binlog
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  app:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: always
    ports:
      - "${NEXTCLOUD_PORT}:80"
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: emi-collection.unifr.ch/nextcloud
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      OVERWRITE_CLI_URL: https://emi-collection.unifr.ch/nextcloud
      #OVERWRITE_HOST: emi-collection.unifr.ch/nextcloud
      #OVERWRITE_PROTOCOL: https
      TRUSTED_PROXIES: 134.21.85.124
      #FORWARDED_FOR_HEADERS: HTTP_X_FORWARDED_FOR
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/wwww/html/
    depends_on:
      - db